### ISSUE TITLE
Having a problem with launching

### ISSUE THREAD

**Issue by Ereshkigal101** [FujiMakoto/twitter-saucenao#1]
For some reason, I keep getting the error, "configparser.NoSectionError:  No section:  'Twitter' " while trying to launch the bot.

**Comment by FujiMakoto** [comment]
This error means the bot can't find your configuration file.

Make sure to copy **config.example.ini** to **config.ini** and configure all the required information,
https://github.com/FujiMakoto/twitter-saucenao/blob/master/config.example.ini
https://github.com/FujiMakoto/twitter-saucenao#documentation

Also make sure you're starting the bot from within the sane directory as the configuration file.

**Comment by Ereshkigal101** [comment]
Ahh there we go, I was launching it an entirely different way, as I normally use .ps1 files to start it when I should've been doing python start.py . Thanks for the help!

**Comment by FujiMakoto** [comment]
No problem, let me know if you run into any other issues!
