### ISSUE TITLE
Implement json.loads dictionary for an automatic list of blocked users

### ISSUE THREAD

**Issue by Zenyaria** [FujiMakoto/twitter-saucenao#15]
This can obviously be done simply, and be very useful for identifying smaller accounts. It can also be expanded as a form of sauce database/character database overlayed on images.

Just a simple suggestion.

I used to hear a lot that json is prone to corruption, but from a year and a half of using it in discordpy, If done correctly, I found it's highly unlikely that corruption would occur.

something as simple as this:

```py
#import json would be at the beginning obv

with open('placeholder.json','r') as data_file:
     blockedusers = json.load(data_file)
USERNAME = str(@{tweet.author}) #can't remember what is used for original tweet usernames, whoops
NICKNAME = str(@{tweet.nickname}) #still can't remember what is used for original tweet usernames...
blockedusers[USERNAME] = {}
blockedusers[USERNAME]['nickname'] = str(NICKNAME)
with open('placeholder.json','w') as data_file:
     json.dump(blockedusers, data_file)
```
then later, you can just print the keys or something, or connect it to some form of google docs API for making spreadsheets.

You could also use this as a method of automating adding saucenao to twitter bots.

**Comment by FujiMakoto** [comment]
I just recently added a commit that adds support for caching via sqlite (or MySQL if configured), so I could easily port your suggestion over and have everything stored in a sqlite table.

From there you can write a script to read from the table and parse everything however you'd like too.

I'll have this implemented this before the next major release.

**Comment by FujiMakoto** [comment]
This has been implemented as mentioned above.

If you need to parse the list of blocked users yourself, you can easily do so with a script like this:
```python
from twsaucenao.models.database import TwitterBlocklist
accounts = [t.screen_name for t in TwitterBlocklist.select()]
```

Which you can then output to a json list or so on if you so wish.
