### ISSUE TITLE
Monitoring another bot

### ISSUE THREAD

**Issue by chizutan5** [FujiMakoto/twitter-saucenao#16]

**Comment by FujiMakoto** [comment]
Hello!

What account are you wishing to have monitored?

**Comment by chizutan5** [comment]
Hi, sorry I thought I added it.
https://twitter.com/KisaragiBot_

**Comment by FujiMakoto** [comment]
Thank you for your interest!

Unfortunately it seems this account hasn't had any media uploads for years and is not actively used, so I cannot add it to the official bots watchlist at this time.

**Comment by chizutan5** [comment]
Hi, it seems that github is incompatible with underscores in urls, the actual account is "@KisaragiBot_"

**Comment by FujiMakoto** [comment]
Sorry for the confusion! I've added your account to the bots monitored accounts list now.
