### ISSUE TITLE
Add support for intelligently processing tweets with multiple images

### ISSUE THREAD

**Issue by FujiMakoto** [FujiMakoto/twitter-saucenao#22]
I've added some code in preparation for this already, just need to implement this as a feature in the next release.

Essentially I'm thinking we'll just parse tweets we're mentioned in for words like "first, second, third, fourth" to get the first, second, etc. image.

Also want to look into parsing for phrases such as "on the right" to parse the second image uploaded if a post only has two images and vice versa for "on the left".

**Comment by Zenyaria** [comment]
You could do both. For pings directly to @saucenao in a multiple image post, it could you redirect you to a temporary page on saucenao.com which has links and information to the images in the post. For the tweet, the bot would post the combined similarity percentage, or a different message entirely linking to the site. Then as you said above, you can do it based upon what the user says. Not sure if this is way you plan to go, though.
