### ISSUE TITLE
ImportError: cannot import name 'SauceNaoResults' from 'pysaucenao.containers'

### ISSUE THREAD

**Issue by Ereshkigal101** [FujiMakoto/twitter-saucenao#32]
Hey once again! I've decided to update since I haven't updated the bot since I first installed it. Anyways, I keep getting this error upon attempting to start it with: python start.py

ImportError: cannot import name 'SauceNaoResults' from 'pysaucenao.containers'

Do you know how to fix this? Thanks in advance!

**Comment by FujiMakoto** [comment]
Hey @Ereshkigal101 !

Can you make sure all the dependencies are up-to-date?

You should be able to do this by running
```pip install -r requirements.txt```
again

**Comment by Ereshkigal101** [comment]
That worked perfectly, thanks a ton! Keep up the great work <3

**Comment by FujiMakoto** [comment]
Happy to hear it! Let me know if you run into any other problems.
