### ISSUE TITLE
DMCA parse request

### ISSUE THREAD

**Issue by Satoshiii-DCS** [FujiMakoto/twitter-saucenao#43]
Target account: [@WaifuSupply](https://twitter.com/WaifuSupply)

I'd like a copy for all of the parse results in a .csv file.

**Comment by FujiMakoto** [comment]
You can find an audit for the account above here:
https://gist.github.com/FujiMakoto/a34036fb6b74261704d7123d3e638ed0

Let me know if there are any questions/concerns!
