### ISSUE TITLE
Please stop tagging the artists.

### ISSUE THREAD

**Issue by chizutan5** [FujiMakoto/twitter-saucenao#47]
Please stop tagging the artists, especially on low accuracy matches.
https://twitter.com/houchi714285/status/1301008570079617024?s=20

I also have seen a few artists complain about being tagged lots.
I can see why since on repetitive bot accounts artists are being tagged a lot for the same few images.

**Comment by FujiMakoto** [comment]
I'll add a filter to exclude Twitter mentions on Very Low accuracy matches, but I don't intend to remove this feature entirely.

People should be able to find the original artists of works on Twitter. I've seen and received many thanks from artists in response to the bot tagging them with credit.

If the bot is too spammy for some I can understand that, and in this case they can simply mute the bot to not receive notifications when it mentions them.
