### ISSUE TITLE
Not getting a reply

### ISSUE THREAD

**Issue by AnymoreMouse** [FujiMakoto/twitter-saucenao#48]
Before the bot was “down” everything works as normal. But now everytime i tag i dont get a reply from the bot no matter how long it took

**Comment by FujiMakoto** [comment]
Hey @AnymoreMouse, we had some issues recently that should be resolved now, I'm really sorry for the inconvenience!

Can you confirm that the issue has been resolved on your end?

**Comment by AnymoreMouse** [comment]
Yes, it has been resolved. Thankss

**Comment by FujiMakoto** [comment]
Awesome, glad to hear it!
