### ISSUE TITLE
Please monitor my account on Twitter

### ISSUE THREAD

**Issue by heybeter** [FujiMakoto/twitter-saucenao#49]
**Requirements**
Due to API restrictions, we have to impose some requirements on account monitoring requests going forward.

Please check all of the following to ensure your account meets the criteria needed for account monitoring.

- [x] My account has at least 5,000 followers
- [x] My account primarily posts anime themed artwork and/or anime screencaps that SauceBot will be able to process
- [x] My account does not post any content in violation of the projects [Code of Conduct](https://github.com/FujiMakoto/twitter-saucenao/blob/master/CODE_OF_CONDUCT.md)
- [x] If my account posts NSFW content, I have properly enabled the "Mark media you Tweet as containing material that may be sensitive" setting on Twitter

**Provide your Twitter screename here**
To avoid accidentally mentioning other Github users, provide only your screename without the @

**Comment by heybeter** [comment]
FaZeFaZeFuckUp

**Comment by FujiMakoto** [comment]
Thank you for your interest in SauceBot!

Unfortunately, I'm afraid your account does not meet the above requirements, therefor we cannot approve your application for account monitoring at this time.
