### ISSUE TITLE
Saucenaopls not working on twitter after maintenance

### ISSUE THREAD

**Issue by heybeter** [FujiMakoto/twitter-saucenao#50]
Seriously, how i make it work again? I got three twitter accounts and all of them refuses to answer, and yes, i tried to a request to monitorize my account, but...what i'm supposed to do? mark the checkboxes? And where i type my twitter username on it? There's no tutoriais whatsoever and i'm VERY noob in these programming steps and stuff. Heeeeeeelp...

**Comment by FujiMakoto** [comment]
Please be sure you have read the following announcement,

https://twitter.com/saucenaopls/status/1311643273774215169

SauceBot will not respond to queries if it cannot find the source of your request. This is to help us prevent the bot from hitting Twitter's daily tweet limits so easily.
