### ISSUE TITLE
Duplicated search request to trace.moe

### ISSUE THREAD

**Issue by soruly** [FujiMakoto/twitter-saucenao#59]
Hi, author of trace.moe here. Recently I've received a lot of requests from your server so I take a look at the traffic and found that you seems to be calling the API twice for every search request. This make the server's overloading condition even worse. Would you take a look?

Now I'm randomly ignoring (HTTP 429-ing) 50% of the requests from your IP address. Hope this would draw your attention.

```
Mon, 12 Apr 2021 18:45:17 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2dcZVoAEKa3e.jpg
Mon, 12 Apr 2021 18:45:18 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2dcZVoAEKa3e.jpg
Mon, 12 Apr 2021 18:45:23 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2e5lWQAAHLtR.jpg
Mon, 12 Apr 2021 18:45:23 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2e5lWQAAHLtR.jpg
Mon, 12 Apr 2021 18:45:39 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2i2fUUAELiG8.jpg
Mon, 12 Apr 2021 18:45:39 +0000 xx.xxx.xx.118 http://pbs.twimg.com/tweet_video_thumb/Eyy2imIXAAExCCb.jpg
Mon, 12 Apr 2021 18:45:39 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2eS7XAAAxKsj.png
Mon, 12 Apr 2021 18:45:40 +0000 xx.xxx.xx.118 http://pbs.twimg.com/tweet_video_thumb/Eyy2imIXAAExCCb.jpg
Mon, 12 Apr 2021 18:45:40 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2i2fUUAELiG8.jpg
Mon, 12 Apr 2021 18:45:40 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2eS7XAAAxKsj.png
Mon, 12 Apr 2021 18:45:45 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2j5oWQAEeJZP.jpg
Mon, 12 Apr 2021 18:45:47 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2j5oWQAEeJZP.jpg
Mon, 12 Apr 2021 18:45:47 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2kazW8AAzPW2.jpg
Mon, 12 Apr 2021 18:45:48 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2lBjWgAkMrED.jpg
Mon, 12 Apr 2021 18:45:48 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2kazW8AAzPW2.jpg
Mon, 12 Apr 2021 18:45:48 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2lBjWgAkMrED.jpg
Mon, 12 Apr 2021 18:45:55 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2mn0WgAIq7HV.jpg
Mon, 12 Apr 2021 18:45:55 +0000 xx.xxx.xx.118 http://pbs.twimg.com/media/Eyy2mn0WgAIq7HV.jpg
```

**Comment by FujiMakoto** [comment]
I believe the duplicated requests are possibly the result of this,
https://github.com/FujiMakoto/twitter-saucenao/blob/75fc3aa2869f270a337a9b90bc512f110d8e8c3f/twsaucenao/sauce.py#L113

Currently it's making one request to the server to look up the source of an image just to verify the anime matches with the result that SauceNao returned (as I use SauceNao for index lookups and trace.moe only for video previews), then it makes a second request just for the video preview.

@soruly can you see if this is the case by chance? Is it making an independent API call to the search endpoint and one to the video endpoint, or is it making two requests on just the search endpoint, or two requests on both endpoints?

**Comment by soruly** [comment]
Nope. It is making two image url search requests. And both requests are
from twitters domain

**Comment by FujiMakoto** [comment]
I can't immediately see any duplicate calls just going over the code, so I'll look into this deeper soon and figure out why it's making extra calls.

**Comment by FujiMakoto** [comment]
@soruly Are you sure this is coming from _my_ address?

The last 3 digits of the IP address in those logs aren't from my server, you'd be seeing requests ending in .202

Additionally, the Twitter saucebot _downloads_ the images from Twitter and sends them as POST requests to your API; you shouldn't be seeing Twitter URL's at all.

So a few questions. First, are those IP logs supposed to be the server the requests are being made from? If they are, maybe it might be someone else running a fork of my bot. or something else entirely? Have you verified these requests contain my Patreon token?

**Comment by soruly** [comment]
You're right. It doesn't look like any requests from your sever, must be someone else.
In fact, the spam traffic stopped just a few days after. And I've updated the current rate limit methods so it should be able to filter such traffic. So all ip bans are removed already.
Sorry to bother you and thanks for the info. `(*>﹏<*)′

**Comment by FujiMakoto** [comment]
Ah, no problem! I'm glad to hear it. 

I definitely don't want to be overburdening your servers more than I probably already am, so just let me know if I ever do need to disable the bots trace.moe queries or anything in the future if it becomes a problem.
