### ISSUE TITLE
Captcha error with Pixiv

### ISSUE THREAD

**Issue by Cknight70** [FujiMakoto/twitter-saucenao#67]
**Describe the bug**
When running the current bot from the master branch with the newest version of pixivpy and cloudscraper I receive an error stating an error with cloudscraper.

**Exception / error logs**
```
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
pixivpy3.utils.PixivError: requests POST https://oauth.secure.pixiv.net/auth/token error: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.
```

**Server (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Python version 3.8.2-0ubuntu2
 - PixivPy 3.5.11
 - cloudscraper 1.2.58
 -  twitter-saucenao efae53d

**Comment by FujiMakoto** [comment]
Are you using a refresh token and not the standard username/password authentication method?

If so, this is unfortunately an issue you'll have to take up with pixivpy3, it's not a library I maintain.
https://github.com/upbit/pixivpy
